#!/usr/bin/env bash

command=$1

remove_dangling(){
    docker rmi $(docker images --filter "dangling=true" -q --no-trunc)
}

dkr_help(){
    printf "dkr dd -> remove all dangling images\n"
}

if [[ ${command} = "dd" ]]; then
    remove_dangling
elif [[ ${command} == "help" ]]; then
	dkr_help
fi