#!/usr/bin/env bash


arg2=$2

on_branch(){
    echo $(git branch | grep "*" | cut -b3-)
}

status(){
    printf "\n$(git status)\n"
}

sync(){
    git add -A
	git stash
	git pull origin $(on_branch)
	git stash apply
}

sync_to(){
    git add -A
	git stash
	git pull origin ${arg2}
	git stash apply
}

push(){
    git add -A
	git commit -m "${arg2}"
	git push origin $(on_branch)
}

gut_help(){
    printf "gut [arg] [message]\n"
    printf "gut s -> runs git status\n"
    printf "gut sync -> runs git add; git stash; git pull; git stash apply\n"
    printf "gut sync-to -> runs git add; git stash; git pull; git stash apply\n"
    printf "gut p [message] -> git add .; git commit -m \"[message]\"; git push\n"
}

command=$1
if [[ ${command} == "s" ]]; then
    status
elif [[ ${command} == "sync" ]]; then
	sync
elif [[ ${command} == "help" ]]; then
	gut_help
elif [[ ${command} == "p" ]]; then
	push
fi
